name: Post X Thread

on:
  schedule:
    - cron: "0 9 */2 * *"  # Every 2 days at 9 AM UTC
  workflow_dispatch:  # Manual trigger

jobs:
  post-thread:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          PEXELS_KEY: ${{ secrets.PEXELS_KEY }}
        run: python main.py

      - name: Commit history and index
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add history.txt topic_index.txt
          git diff-index --quiet HEAD || (git commit -m "Update history and topic index" --allow-empty)
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
